version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./vendor:/var/www/html/vendor
            - ./node_modules:/var/www/html/node_modules
        ports:
            - "8000:80"
        networks:
            - laravel_network
        depends_on:
            - db
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: laravel

    db:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    db_data:
        driver: local
